# =================================================================================
# LANGGRAPH STREAMING CHEAT SHEET (For Future Reference)
# =================================================================================
# LangGraph supports streaming updates during graph execution. This allows you to
# stream individual tokens (for LLM text generation) or step updates (as nodes complete).
# 
# Main streaming modes available in `graph.stream()`:
# 1. "values": Streams the full state dictionary after every node execution.
# 2. "updates": Streams only the specific updates returned by the node that just finished.
# 3. "messages": Streams LLM tokens and message updates in real-time (chunk-by-chunk).
# 4. "debug": Streams internal events, transitions, and state changes for debugging.
# =================================================================================

# ---------------------------------------------------------------------------------
# APPROACH 1: Streaming Node Updates ("updates" mode)
# Use case: Tracking which node executed and what data/messages it just produced.
# ---------------------------------------------------------------------------------
# input_data = {"messages": [HumanMessage(content="Hello")]}
# for chunk in graph.stream(input_data, stream_mode="updates"):
#     # chunk structure: { "node_name": { "state_key": updated_value } }
#     for node, data in chunk.items():
#         print(f"\n--- Node '{node}' finished executing ---")
#         print(f"Node output: {data}")


# ---------------------------------------------------------------------------------
# APPROACH 2: Streaming LLM Tokens in Real-Time ("messages" mode)
# Use case: Showing words on the UI as they are generated by the model (ChatGPT style).
# ---------------------------------------------------------------------------------
# input_data = {"messages": [HumanMessage(content="Write a long essay")]}
# for message, metadata in graph.stream(input_data, stream_mode="messages"):
#     # 'message' is a chunk object (e.g., AIMessageChunk) containing text tokens
#     # 'metadata' contains context like the node name that generated the message
#     if metadata.get("langgraph_node") == "chatbot":
#         print(message.content, end="", flush=True)


# ---------------------------------------------------------------------------------
# APPROACH 3: Streaming Full State ("values" mode)
# Use case: Fetching the entire historical state stack after every single step.
# ---------------------------------------------------------------------------------
# input_data = {"messages": [HumanMessage(content="Hello")]}
# for state in graph.stream(input_data, stream_mode="values"):
#     # state structure: The entire updated State dictionary (e.g., ChatState)
#     print(f"Current message count in history: {len(state['messages'])}")


# =================================================================================
# QUICK SUMMARY OF STREAMING BEHAVIOUR
# =================================================================================
# - Use async graph execution (`await graph.astream(...)`) for better performance in APIs.
# - Multi-mode streaming can be achieved by passing a list: `stream_mode=["updates", "messages"]`.
# - Ensure your underlying LLM has `streaming=True` turned on in its setup function
#   (e.g., `ChatOpenAI(model="gpt-4o", streaming=True)`) to make token streaming work.
# =================================================================================


import streamlit as st
from _0_chatbot_backend import chatbot
from langchain_core.messages import HumanMessage

st.title("Agentic Chatbot")

#set a specif config for each session as st.session_state -> dict -> 
CONFIG = {'configurable': {'thread_id': 'thread-1'}}

#use session state to store the message history to display all the conversation in the frontend
#use st.session_state as list because stremlit does not support dict as session state, so we use list to store the message history
if 'message_history' not in st.session_state:
    st.session_state['message_history'] = []

# loading the conversation history and showing it in the frontend
for message in st.session_state['message_history']:
    with st.chat_message(message['role']):
        st.text(message['content'])

# take user input
user_input = st.chat_input('Type here')

#if user input is not empty, then send the user input to the backend and get the response from the backend
if user_input:

    # first add the message to message_history
    st.session_state['message_history'].append({'role': 'user', 'content': user_input})
    with st.chat_message('user'):
        st.text(user_input)

    # first add the message to message_history and then display the message in the frontend
    with st.chat_message('assistant'):

           ai_message = st.write_stream(
                message_chunk for message_chunk,metadata in chatbot.stream(
                     {'messages': [HumanMessage(content=user_input)]},
                     config=CONFIG,
                     stream_mode="messages"  #mode =messages for real time streaming of LLM tokens
                )
           )
    st.session_state['message_history'].append({'role': 'assistant', 'content': ai_message})
    



